# Generated by Django 3.2.9 on 2021-11-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
